name: NASA Project CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js version 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm ci 

      - name: Install server dependencies
        run: npm ci --prefix server

      - name: Install client dependencies
        run: npm ci --prefix client

      - name: Build client
        run: npm run build --prefix client
